### ISSUE TITLE
Select integration dropdown is empty

### ISSUE THREAD

**Issue by lookitsbeau** [activeprospect/leadconduit-integration-highrise#5]
![pasted image at 2015_09_30 10_10 am](https://cloud.githubusercontent.com/assets/1291126/10197234/34c3f6d4-675c-11e5-89ba-53637856f720.png)

**Comment by cgrayson** [comment]
I was updating the API seed file anyway, so it's my [commit](https://github.com/activeprospect/leadconduit-api/commit/d88babb857de1e099943b04daeb14b7ae83df67a), but @jgrayson676 found what was wrong. :+1: Fixed in API 3.9.6.
